# Generated by Django 3.0 on 2025-03-05 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("oc_lettings_site", "0001_initial")]

    database_operations = [
        migrations.AlterModelTable("Letting", "letting_letting"),
        migrations.AlterModelTable("Address", "letting_address"),
        migrations.AlterModelTable("Profile", "user_profile_profile"),
    ]

    state_operations = [
        migrations.DeleteModel("Letting"),
        migrations.DeleteModel("Address"),
        migrations.DeleteModel("Profile"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        )
    ]
